---
kind: pipeline
type: docker
name: default
steps:
  - name: test
    image: node:alpine
    commands:
    - npm install
    - npm run coverage

  - name: coveralls
    image: lizheming/drone-coveralls
    settings:
      token:
        from_secret: coveralls_token
      files:
      - /drone/src/lcov.info
