---
kind: pipeline
type: docker
name: default
steps:
  - name: test
    image: node:alpine
    commands:
    - npm install
    - npm run test
  - name: coverage
    image: node:alpine
    commands:
      - npm run coverage
    environment:
      COVERALLS_REPO_TOKEN:
        from_secret: coveralls_token
